# -*- coding: utf-8 -*-
"""AmruLLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdsRa_tpp9IiYPxeD78VozCeu5Xq4ITU
"""

# !pip install openai pandas

# !pip install openai==0.28

import openai
import os
import pandas as pd

# Set your OpenAI API key
# os.environ["OPENAI_API_KEY"] = "your_api_key"

# Load your dataset (assuming it's a CSV file)
data = pd.read_csv('galle_route_questions_dataset.csv')

# Inspect the dataset
# print(data.head())

def find_route(question, data):
    # Match the input question with the dataset and retrieve the response
    row = data[data['Question'].str.contains(question, case=False, na=False)]
    if not row.empty:
        route = row['Route Options'].values[0]
        landmarks = row['Popular Landmarks'].values[0]
        activities = row['Activities'].values[0]
        return route, landmarks, activities
    else:
        return "No matching route found.", "", ""

# Test the function
# question = "Is there a recommended route from Bentota to Rumassala?"
# route, landmarks, activities = find_route(question, data)
# print(f"Route: {route}\nLandmarks: {landmarks}\nActivities: {activities}")

# Call OpenAI API using the new ChatCompletion method
def get_openai_response(question):
    openai.api_key = os.getenv("OPENAI_API_KEY")

    # Prepare the system prompt
    system_prompt = f"""
    You are a travel chatbot. Your job is to help users find travel information based on a question.

    Question: {question}

    Return the corresponding:
    - Route Options
    - Popular Landmarks
    - Activities
    """

    # Call OpenAI API with the new ChatCompletion method
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful travel assistant within Galle, Sri Lanka, providing bus travel advice with multiple route options."},
            {"role": "user", "content": question},
        ],
        max_tokens=150,
        n=1,  # Number of completions to return
        stop=None,  # You can add a stop sequence if needed
        temperature=0.7  # Adjust the creativity level of the response
    )

    return response['choices'][0]['message']['content'].strip()

# Test OpenAI API response
# question = "What's the best route from Unawatuna Beach to Matara?"
# response = get_openai_response(question)
# print(response)

# test_question = "How can I go from Mirissa to Hikkaduwa?"
# response = get_openai_response(question)
# print(response)